use super::*;

//Articles
pub static mut FIGHTER_SPRINGTRAP_GENERATE_ARTICLE_AXE: i32 = 2;
pub static mut FIGHTER_SPRINGTRAP_GENERATE_ARTICLE_PHANTOM: i32 = 2;

//Springtrap Instance Work ID
pub const FIGHTER_SPRINGTRAP_INSTANCE_WORK_ID_FLAG_ACTIVE_AXE: LuaConst = LuaConst::new(0x200000E6);
pub const FIGHTER_SPRINGTRAP_INSTANCE_WORK_ID_FLAG_SPECIAL_N_CHARGED: LuaConst = LuaConst::new(0x200000E7);
pub const FIGHTER_SPRINGTRAP_INSTANCE_WORK_ID_FLAG_ACTIVE_PHANTOM: LuaConst = LuaConst::new(0x200000E8);
pub const FIGHTER_SPRINGTRAP_INSTANCE_WORK_ID_FLOAT_SPECIAL_S_CHARGE: LuaConst = LuaConst::new(0x4E);
pub const FIGHTER_SPRINGTRAP_INSTANCE_WORK_ID_INT_SPECIAL_HI_ROT_ANGLE: LuaConst = LuaConst::new(0x100000C5);
pub const FIGHTER_SPRINGTRAP_INSTANCE_WORK_ID_INT_SPECIAL_HI_MOVE_TIME: LuaConst = LuaConst::new(0x100000C6);
pub const FIGHTER_SPRINGTRAP_INSTANCE_WORK_ID_INT_EFFECT_ID: LuaConst = LuaConst::new(0x100000C7);
pub const FIGHTER_SPRINGTRAP_INSTANCE_WORK_ID_INT_SPECIAL_LW_PHANTOM_TYPE: LuaConst = LuaConst::new(0x100000C8);

//Springtrap Status Kind
pub const FIGHTER_SPRINGTRAP_STATUS_KIND_SPECIAL_N_CHARGE_LOOP: LuaConst = LuaConst::new(0x1F3);
pub const FIGHTER_SPRINGTRAP_STATUS_KIND_SPECIAL_N_LOW_FIRE: LuaConst = LuaConst::new(0x1F4);
pub const FIGHTER_SPRINGTRAP_STATUS_KIND_SPECIAL_N_HIGH_FIRE: LuaConst = LuaConst::new(0x1F5);
pub const FIGHTER_SPRINGTRAP_STATUS_KIND_SPECIAL_N_RECALL_START: LuaConst = LuaConst::new(0x1F6);
pub const FIGHTER_SPRINGTRAP_STATUS_KIND_SPECIAL_N_RECALL_LOOP: LuaConst = LuaConst::new(0x1F7);
pub const FIGHTER_SPRINGTRAP_STATUS_KIND_SPECIAL_N_RECALL_END: LuaConst = LuaConst::new(0x1F8);
pub const FIGHTER_SPRINGTRAP_STATUS_KIND_SPECIAL_S_HOLD: LuaConst = LuaConst::new(0x1F9);
pub const FIGHTER_SPRINGTRAP_STATUS_KIND_SPECIAL_S_ATTACK: LuaConst = LuaConst::new(0x1FA);
pub const FIGHTER_SPRINGTRAP_STATUS_KIND_SPECIAL_HI_MOVE: LuaConst = LuaConst::new(0x1FB);
pub const FIGHTER_SPRINGTRAP_STATUS_KIND_SPECIAL_HI_END: LuaConst = LuaConst::new(0x1FC);

/* 
Springtrap Axe Instance Work ID

Axe Flag Start: 0x2000000B
Axe Float Start: 0x7
Axe Int Start: 0x10000017
*/
pub const WEAPON_SPRINGTRAP_AXE_INSTANCE_WORK_ID_FLAG_LINKED: LuaConst = LuaConst::new(0x2000000B);
pub const WEAPON_SPRINGTRAP_AXE_INSTANCE_WORK_ID_INT_OBJECT_ID: LuaConst = LuaConst::new(0x10000017);

//Springtrap Axe Status Kind
pub const WEAPON_SPRINGTRAP_AXE_STATUS_KIND_FLY: LuaConst = LuaConst::new(0x0);
pub const WEAPON_SPRINGTRAP_AXE_STATUS_KIND_STICK: LuaConst = LuaConst::new(0x1);
pub const WEAPON_SPRINGTRAP_AXE_STATUS_KIND_HIT_STICK: LuaConst = LuaConst::new(0x2);
pub const WEAPON_SPRINGTRAP_AXE_STATUS_KIND_RECALL: LuaConst = LuaConst::new(0x3);

/*
Springtrap Phantom Instance Work ID

Phantom Flag Start: 0x20000011
Phantom Float Start: 0x6
Phantom Int Start: 0x1000000C
*/
pub const WEAPON_SPRINGTRAP_PHANTOM_INSTANCE_WORK_ID_FLOAT_OWNER_INIT_LR: LuaConst = LuaConst::new(0x6);
pub const WEAPON_SPRINGTRAP_PHANTOM_INSTANCE_WORK_ID_FLOAT_BB_SPEED_X: LuaConst = LuaConst::new(0x7);
pub const WEAPON_SPRINGTRAP_PHANTOM_INSTANCE_WORK_ID_FLOAT_BB_SPEED_Y: LuaConst = LuaConst::new(0x8);
pub const WEAPON_SPRINGTRAP_PHANTOM_INSTANCE_WORK_ID_INT_PHANTOM_TYPE: LuaConst = LuaConst::new(0x1000000C);

//Springtrap Phantom Status Kind
pub const WEAPON_SPRINGTRAP_PHANTOM_STATUS_KIND_PHANTOM_SUMMON: LuaConst = LuaConst::new(0x0);
pub const WEAPON_SPRINGTRAP_PHANTOM_STATUS_KIND_PHANTOM_EXPLODE: LuaConst = LuaConst::new(0x1);
pub const WEAPON_SPRINGTRAP_PHANTOM_STATUS_KIND_PHANTOM_BREAK: LuaConst = LuaConst::new(0x2);
pub const WEAPON_SPRINGTRAP_PHANTOM_STATUS_KIND_BB_IDLE: LuaConst = LuaConst::new(0x3);
pub const WEAPON_SPRINGTRAP_PHANTOM_STATUS_KIND_BB_FALL: LuaConst = LuaConst::new(0x4);
pub const WEAPON_SPRINGTRAP_PHANTOM_STATUS_KIND_CHICA_WALK: LuaConst = LuaConst::new(0x5);
pub const WEAPON_SPRINGTRAP_PHANTOM_STATUS_KIND_CHICA_FALL: LuaConst = LuaConst::new(0x6);
pub const WEAPON_SPRINGTRAP_PHANTOM_STATUS_KIND_CHICA_TURN: LuaConst = LuaConst::new(0x7);
pub const WEAPON_SPRINGTRAP_PHANTOM_STATUS_KIND_CHICA_ATTACK: LuaConst = LuaConst::new(0x8);
pub const WEAPON_SPRINGTRAP_PHANTOM_STATUS_KIND_FOXY_ATTACK: LuaConst = LuaConst::new(0x9);
pub const WEAPON_SPRINGTRAP_PHANTOM_STATUS_KIND_FREDDY_WALK: LuaConst = LuaConst::new(0xA);
pub const WEAPON_SPRINGTRAP_PHANTOM_STATUS_KIND_FREDDY_FALL: LuaConst = LuaConst::new(0xB);
pub const WEAPON_SPRINGTRAP_PHANTOM_STATUS_KIND_FREDDY_TURN: LuaConst = LuaConst::new(0xC);
pub const WEAPON_SPRINGTRAP_PHANTOM_STATUS_KIND_FREDDY_ATTACK: LuaConst = LuaConst::new(0xD);

//Phantom IDs
pub const SPRINGTRAP_PHANTOM_TYPE_BALLOON_BOY: LuaConst = LuaConst::new(0x0);
pub const SPRINGTRAP_PHANTOM_TYPE_CHICA: LuaConst = LuaConst::new(0x1);
pub const SPRINGTRAP_PHANTOM_TYPE_FOXY: LuaConst = LuaConst::new(0x2);
pub const SPRINGTRAP_PHANTOM_TYPE_FREDDY: LuaConst = LuaConst::new(0x3);

//Phantom Hurtbox
pub const WEAPON_SPRINGTRAP_PHANTOM_SHIELD_KIND_BALLOON_BOY_BODY: LuaConst = LuaConst::new(0x0);

//Collision Sound
pub const COLLISION_SOUND_ATTR_SPRINGTRAP_KNIFE: LuaConst = LuaConst::new(0x8D);